version: "3.1"
services:
  db:
    image: mariadb:latest

    ports:
      - "3305:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbRestaurante
      MYSQL_USER: javi2
      MYSQL_PASSWORD: javi2
      MYSQL_ROOT_PASSWORD: javi
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: javi
volumes:
  persistent:

