ktor:
    application:
        modules:
            - com.example.ktor.ApplicationKt.module
    deployment:
        port: 8089

    database:
        driver: "org.mariadb.jdbc.Driver"
        url: "jdbc:mariadb://localhost:3307/dbRestaurante"
        username: "javi"
        password: "javi"